### ISSUE TITLE
License suggestion

### ISSUE THREAD

**Issue by billdenney** [kestrel99/nlmixr2_book#1]
I clicked on the license link, and it suggested using version 4.0 of the license rather than 3.0 (https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en).

https://github.com/kestrel99/nlmixr2_book/blob/782c63bea864f8460164d92f081b8f4c943f8db8/index.qmd#L9

**Comment by kestrel99** [comment]
This is fine. It may need to change later anyway, if we decide to produce a physical copy.
